- name: remove existing directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend folder /app, fronend /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend folder /app, fronend /usr/share/nginx/html
    state: directory # when create use directory

- name: download app code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v3.zip"
    dest: "{{ APP_LOCATION }}" # this will unzip code here
    remote_src: yes